# fly.toml app configuration file generated for bold-surf-6128 on 2023-09-14T14:17:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xyzexphen"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
